In [1]:
import numpy as np 
import pandas as pd

In [3]:
df = pd.read_csv(r"C:\Users\dhruv\Downloads\spam (7).csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [6]:
df['spam'] = df['Category'].apply(lambda x :1 if x == 'spam' else 0)

In [7]:
df.shape

(5572, 3)

In [8]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

# Train_test_split

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.Message,df.spam,test_size = 0.2)

In [12]:
X_train.shape

(4457,)

In [14]:
X_train[:4]

4124    Cool, want me to go to kappa or should I meet ...
800               Gimme a few was  &lt;#&gt;  minutes ago
1933                            Jus finished avatar nigro
5402    Hi babe its me thanks for coming even though i...
Name: Message, dtype: object

# Create Bag of words representation using count vectorizer

In [16]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<4457x7723 sparse matrix of type '<class 'numpy.int64'>'
	with 59580 stored elements in Compressed Sparse Row format>

In [17]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [18]:
X_train_cv.shape

(4457, 7723)

In [19]:
v.get_feature_names_out()[1771]

'chest'

In [20]:
v.vocabulary_

{'cool': 2002,
 'want': 7349,
 'me': 4383,
 'to': 6907,
 'go': 3151,
 'kappa': 3877,
 'or': 4948,
 'should': 6097,
 'meet': 4401,
 'you': 7682,
 'outside': 4994,
 'mu': 4608,
 'gimme': 3128,
 'few': 2809,
 'was': 7363,
 'lt': 4230,
 'gt': 3252,
 'minutes': 4481,
 'ago': 867,
 'jus': 3854,
 'finished': 2852,
 'avatar': 1156,
 'nigro': 4754,
 'hi': 3410,
 'babe': 1190,
 'its': 3751,
 'thanks': 6779,
 'for': 2933,
 'coming': 1914,
 'even': 2651,
 'though': 6839,
 'it': 3744,
 'didnt': 2296,
 'that': 6785,
 'well': 7425,
 'just': 3855,
 'wanted': 7351,
 'my': 4639,
 'bed': 1286,
 'hope': 3475,
 'see': 5962,
 'soon': 6295,
 'love': 4207,
 'and': 961,
 'kisses': 3926,
 'xxx': 7634,
 'lol': 4165,
 'real': 5574,
 'she': 6054,
 'told': 6923,
 'dad': 2142,
 'have': 3349,
 'cancer': 1639,
 'call': 1607,
 'him': 3418,
 'tell': 6731,
 'now': 4815,
 'infront': 3662,
 'of': 4869,
 'them': 6797,
 'how': 3505,
 'stupid': 6526,
 'say': 5904,
 'challenge': 1716,
 'god': 3157,
 'dont': 2402,
 'think': 682

In [21]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [22]:
np.where(X_train_np[0]!=0)

(array([2002, 3151, 3877, 4383, 4401, 4608, 4948, 4994, 6097, 6907, 7349,
        7682], dtype=int64),)

In [26]:
X_train_np[0][1771]

0

# Train the naive bayes model

In [27]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [28]:
X_test_cv = v.transform(X_test)

# Evaluate Performance

In [29]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       961
           1       0.99      0.92      0.95       154

    accuracy                           0.99      1115
   macro avg       0.99      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115



# Train the model using sklearn pipeline and reduce number of lines of code

In [30]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [31]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [32]:
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       961
           1       0.99      0.92      0.95       154

    accuracy                           0.99      1115
   macro avg       0.99      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115

